### ISSUE TITLE
clarification is  npm install mysql-live-select needed with numtel:sql server 

### ISSUE THREAD

**Issue by noah2828** [numtel/meteor-mysql#18]
do i need to install the mysql-live-select with numtel:sql and numtel:sql server?  
thanks

**Comment by numtel** [comment]
The `mysql-live-select` NPM package is loaded by the `numtel:mysql` Meteor package. It is loaded on the server side of your application and is referenced by the global `LiveMysql` object.

`numtel:mysql-server` is optional, providing an easy way to install a MySQL server directly as part of your Meteor application. If you don't have MySQL installed and provided you're using Linux or Mac OSX (Windows support is not yet available), you can skip any extra installation or configuration, similarly to how Mongo is included with Meteor.
