### ISSUE TITLE
Client isn't updated when no records are returned

### ISSUE THREAD

**Issue by darkadept** [numtel/meteor-mysql#19]
When calling `.change()` on a `MysqlSubscription` and the server returns a SQL query with 0 records, the client does not get updated.

I'm publishing a simple list of names from the server like this:

    var livedb = new LiveMysql(Meteor.settings.mysql);
    Meteor.publish('names', function(doBlank) {
      var sql;
      if (doBlank) {
        sql = "SELECT name FROM names WHERE name = 'notGoingToMatch'";
      } else {
        sql = "SELECT name FROM names";
      }

      return livedb.select(sql, [{table:'names'}]);
    }

On the client I have a helper and event:

    var mySub = new MysqlSubscription('names');
    Template.myTemplate.helpers({
      myData: function() {
        return mySub.reactive();
      }
    });

    Template.myTemplate.events({
      'click #getBlank': function(ev, tmpl) {
        mySub.change(true);
      }
    });

On first load the client shows a list of names (using the `myData` helper), but when I click the #getBlank` button instead of showing 0 records, it still shows the initial records.

**Comment by numtel** [comment]
Thanks for the issue. I just made a test case to check for this and it fails: 

https://travis-ci.org/numtel/meteor-mysql/builds/65466323

I'll try to make a fix for this tonight.

**Comment by numtel** [comment]
Ok, I have released version 0.1.9 which fixes this issue.
