### ISSUE TITLE
Keep trigger polling method in separate branch

### ISSUE THREAD

**Issue by rclai** [numtel/meteor-mysql#2]
Good work on this.

I might need this method.

**Comment by numtel** [comment]
Sounds good, it definitely has less involved installation requirements so there is a space for it but if you want to run more than one Meteor server connected to a single MySQL database, you'll run into issues with triggers overlapping. Obviously, this could be fixed but it would be time consuming and very tough to make optimal.

**Comment by numtel** [comment]
The separate branch now exists:

https://github.com/numtel/meteor-mysql/tree/old
