### ISSUE TITLE
Cannot subscribe using iron router?

### ISSUE THREAD

**Issue by LinkXXI** [numtel/meteor-mysql#26]
I'm having trouble getting a subscription to work in the waitOn of iron router, I have no idea if I'm doing this right but here is the code that I am working with.

router route:

    Router.route('/:extension',{
        name:'Root Extension',
        template: "CSABoard",
        waitOn: function () {
            return new MysqlSubscription('userStatus', this.params.extension);
        },
        data: function () {
            return this.params.extension;
        }
    });

publication:

    Meteor.publish('userStatus', function(extension){
        //liveDb var is called thor
        thor.select(
            'SELECT * FROM ' +
            'cs_agent_log ' +
            'WHERE ext = ' + thor.db.escape(extension) +' ' +
            'ORDER BY date_created ' +
            'DESC',
            [
                {
                    table: 'cs_agent_log',
                    condition: function (row){
                        return row.ext === extension;
                    }
                }
        ]);
    });

The error returned is: 

    Exception in callback of async function: Error: Subscription failed!
    at Array.MysqlSubscription (http://localhost:3000/packages/numtel_mysql.js?4552b8ecdd7ac8567ba8d3f82472cf5220f44d89:77:34)

**Comment by LinkXXI** [comment]
I'm an idiot, this is most definitely not how this is meant to be used....

**Comment by sclausen** [comment]
Hello LinkXXI, from idiot, to idiot: How is it meant to be used with iron:router? :D

**Comment by LinkXXI** [comment]
@sclausen The object returned is not a Meteor subscription object. Putting it in the waitOn of a route will work, but there is no way to access the object after that.

Also, it won't actually wait on the result since it returns an empty array before the results are loaded.]

I ended up calling the publication directly from the created event of the template I was using.

**Comment by gabischmidberger** [comment]
I have the same problem. Does anybody have a solution using something like the the Router.route solution above

**Comment by kiyasov** [comment]
HELP
