### ISSUE TITLE
How to get added records if there's a LIMIT in the SQL statement?

### ISSUE THREAD

**Issue by sushitommy** [numtel/meteor-mysql#27]
Hi there,

I've got the following line:
var cursor = conn.liveDB.select("SELECT * FROM "+conn.table+" LIMIT 20", [ { table: conn.table } ]);

The 'added' event does not fire when a new row is added.
How can I listen for rows being added with a limit in the SQL statement?

**Comment by numtel** [comment]
What do you mean? For instance, if there are 10 results with a limit of 20 and one row is inserted, the `added` event does not get fired? Or if there are 20 results and another row is inserted, the `added` event isn't called even though the new row takes the place of one that existed previously?

If yes to the latter, this is related to https://github.com/numtel/meteor-mysql/issues/14#issuecomment-131548996

**Comment by sushitommy** [comment]
It's the latter indeed, I read #14 before but how does this relate?

**Comment by numtel** [comment]
It has to do with the way the difference between result sets is calculated. Until this is updated, I would think you're probably going to get a ´changed´ event in that case.

I think I'll be able to fix this in about 2 weeks but maybe sooner.

**Comment by sushitommy** [comment]
You're right the 'changed' event is emitted.

**Comment by numtel** [comment]
See new version 1.0.0 with the updated difference calculator. This change reports all changes in the `diff` argument of the `update` event. The old `added`, `changed`, and `removed` events were rarely correct with their matching of the rows. Hopefully this is an improvement, the data transferred to the client should be much less now.

**Comment by sushitommy** [comment]
Hey Ben,

Great, I think this solution is much more elegant.

One thing:
Let's say we have a mysql table where new rows get inserted every 200 ms (5 per second).
The minInterval is set to 1000 ms.
Before, the "SELECT * FROM table LIMIT 5" query on this table would fire 5 added events and then 5 changed events on every update.
With the updated difference calculator, it now fires one event every second with one row in the diff object. However all rows in the query are changed.
Shouldn't all changed rows be returned?

Regards,
Tom

**Comment by sushitommy** [comment]
Hey Ben,
great work, this solution is much more elegant.

Tom
