### ISSUE TITLE
Can MysqlSubscription be implemented in client only?

### ISSUE THREAD

**Issue by HosseinAgha** [numtel/meteor-mysql#29]
I wanted to thank you for your package, it saved me a lot of mysql to mongo migration headache!
I put MysqlSubscription in client code only and your mysql leaderboards example still works perfectly.
Why should we implement it in server?

**Comment by numtel** [comment]
I do not understand what you are asking. If you want to have a collection of results without being connected to a database, why not use an array?

**Comment by HosseinAgha** [comment]
Sorry I think i couldn't explain what I mean.
Can you explain why we need to call `MysqlSubscription` both on client and server (based on your readme)?   Because meteor doc says we must call `Meteor.subscribe` on client only. Aren't they basically the same?

**Comment by numtel** [comment]
You do not have to create the subscription on both the client and server. The interface works on both though in case you want to.

If you're writing live queries that live only on the server though, you're better off just listening to the events from mysql-live-select.
