### ISSUE TITLE
using numtel:mysql with simple:rest

### ISSUE THREAD

**Issue by juliuscarvajal** [numtel/meteor-mysql#35]
This package is awesome. Great stuff.

I am currently using this package with simple:rest but I hit a snag:

```
I20150921-16:08:50.683(10)? Internal server error in publications/locations [TypeError: Object #<LiveMysqlSelect> has no method 'fetch'] TypeError: Object #<LiveMysqlSelect> has no method 'fetch'
I20150921-16:08:50.685(10)?     at httpPublishCursor (packages/simple:rest/rest.js:161:1)
I20150921-16:08:50.685(10)?     at packages/simple:rest/rest.js:44:1
I20150921-16:08:50.685(10)?     at catchAndReportErrors (packages/simple:rest/rest.js:241:1)
I20150921-16:08:50.685(10)?     at packages/simple:rest/rest.js:25:1
I20150921-16:08:50.685(10)?     at packages/simple:json-routes/json-routes.js:45:1
```
Any ideas?

The (redacted) code below:
```
Locations = new MysqlSubscription('locations');

var liveDb = new LiveMysql({
/*...*/
});

Meteor.publish('locations', function () {
  return liveDb.select(
    'select * from channel', [{
      table: 'channel'
    }]
  );
});
```

I originally posted this issue to simple:rest
https://github.com/stubailo/meteor-rest/issues/60

**Comment by numtel** [comment]
I haven't tested this but I would guess that if you put the following line on your server side code, it should make it work.

```javascript 
LiveMysql.LiveMysqlSelect.fetch = LiveMysql.LiveMysqlSelect.reactive;
```

Let me know if the does the trick. If so, I'll release a new version with the update. Otherwise, give me a couple days to come up with the fix.

**Comment by juliuscarvajal** [comment]
Does not work, mate. Looking forward for a fix. Let me know if you need any other info.
Cheers.

**Comment by numtel** [comment]
Ok, give new version 1.0.3 a look.

In the test case, you'll notice that the data is not sorted in the REST JSON output so you have to do this yourself on the client manually.

**Comment by juliuscarvajal** [comment]
Cool. That was quick. Will check this out now. Thanks, mate.

**Comment by juliuscarvajal** [comment]
You're a legend. It's working now.

```
{
  "data": [
    {
      "_id": "1",
      "id": 1,
      "colour_id": null,
      "code": null,
      "name": "Location 1",
      "location": "from sails etetet",
      "timezone": null,
      "data": null,
      "_index": 1
    },
    {
      "_id": "2",
      "id": 2,
      "colour_id": null,
      "code": null,
      "name": "Location 2",
      "location": "dddddd",
      "timezone": null,
      "data": null,
      "_index": 2
    },
    {
      "_id": "3",
      "id": 3,
      "colour_id": null,
      "code": null,
      "name": "Location 3",
      "location": "Location 3",
      "timezone": null,
      "data": null,
      "_index": 3
    },
    {
      "_id": "4",
      "id": 4,
      "colour_id": null,
      "code": null,
      "name": "Location 4",
      "location": "4 Fake St",
      "timezone": null,
      "data": null,
      "_index": 4
    },
    {
      "_id": "5",
      "id": 5,
      "colour_id": null,
      "code": null,
      "name": "Location 5",
      "location": "5 Fake St",
      "timezone": null,
      "data": null,
      "_index": 5
    }
  ]
}
```

Cheers.

**Comment by numtel** [comment]
Awesome it works for you :smile_cat: What else was I going to do on an airplane today? :sunglasses: 

I don't know what it did to my Travis CI tests though... gotta figure that one out now

https://travis-ci.org/numtel/meteor-mysql/builds/81520727

**Comment by juliuscarvajal** [comment]
A plane ride would do the trick for your Travis CI tests :smiley_cat: 
By the way, it would be more awesome to add ORM stuff to your already amazing mysql package (instead of writing sql queries in the publish functions).

**Comment by numtel** [comment]
I don't have any plans to write ORM features on my own but if it's something you're interested in, please send me an email, possibly with some examples of an ORM or two that you like. I am available for contract work and would be happy to work on such a project.
