### ISSUE TITLE
How to handle NULL value in column data ?

### ISSUE THREAD

**Issue by khichar-anil** [numtel/meteor-mysql#43]
My UI is breaking when a record is having NULL value in database.

Is there any workaround to replace null with blank string on the fly.

**Comment by numtel** [comment]
Do you have a stack trace or a repo I can clone to see this? I'll get on my computer and double check soon but I don't think this should cause a problem.

**Comment by numtel** [comment]
I'm going to close this because I have found no problems with NULL values. It must be a problem with your front end code. Please comment with more information if otherwise.

**Comment by anil-kumar-ma** [comment]
Thanks for your prompt reply. It was angular filter which was breaking with null values. Now I handled it in mysql queries like:
ifnull(filed,'')

Actually initially we were using mongo db with meteor which was giving blank values for any null field but now we switched to mysql where it started giving null and hence angular filter broken.
