### ISSUE TITLE
Cannot enqueue Query after fatal error

### ISSUE THREAD

**Issue by rohitmehrotramedia** [numtel/meteor-mysql#45]
Hi numtel, 

I facing "Cannot enqueue Query after fatal error" issue on my local server with meteor . I have successfully enable the bin log and also double check the configuration things . Please help me to sort out the error it will be really appreciated.

I am using macbook pro os X and mysql server version is 5.0.11.

Complete issue as follow.

20151103-19:57:55.557(5.5)? Exception from sub questions id XmKgm9D7SxwN8gsQa Error: Cannot enqueue Query after fatal error.
I20151103-19:57:55.558(5.5)?     at Object.Future.wait (/Users/RCMehrotra/.meteor/packages/meteor-tool/.1.1.10.4oz6g6++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
I20151103-19:57:55.558(5.5)?     at LiveMysqlSelect.LiveMysql.LiveMysqlSelect._publishCursor (packages/numtel_mysql/packages/numtel_mysql.js:55:1)
I20151103-19:57:55.558(5.5)?     at [object Object]._.extend._publishHandlerResult (livedata_server.js:1065:13)
I20151103-19:57:55.558(5.5)?     at [object Object]._.extend._runHandler (livedata_server.js:1038:10)
I20151103-19:57:55.559(5.5)?     at [object Object]._.extend._startSubscription (livedata_server.js:842:9)
I20151103-19:57:55.559(5.5)?     at [object Object]._.extend.protocol_handlers.sub (livedata_server.js:614:12)
I20151103-19:57:55.559(5.5)?     at livedata_server.js:548:43
I20151103-19:57:55.559(5.5)?     - - - - -
I20151103-19:57:55.560(5.5)?     at Protocol._validateEnqueue (/Users/RCMehrotra/.meteor/packages/numtel_mysql/.1.0.3.1xnfqbt++os+web.browser+web.cordova/npm/node_modules/mysql/lib/protocol/Protocol.js:193:16)
I20151103-19:57:55.560(5.5)?     at Protocol._enqueue (/Users/RCMehrotra/.meteor/packages/numtel_mysql/.1.0.3.1xnfqbt++os+web.browser+web.cordova/npm/node_modules/mysql/lib/protocol/Protocol.js:129:13)
I20151103-19:57:55.560(5.5)?     at Connection.query (/Users/RCMehrotra/.meteor/packages/numtel_mysql/.1.0.3.1xnfqbt++os+web.browser+web.cordova/npm/node_modules/mysql/lib/Connection.js:201:25)
I20151103-19:57:55.561(5.5)?     at update (/Users/RCMehrotra/.meteor/packages/numtel_mysql/.1.0.3.1xnfqbt++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/lib/QueryCache.js:72:18)
I20151103-19:57:55.561(5.5)?     at QueryCache.invalidate (/Users/RCMehrotra/.meteor/packages/numtel_mysql/.1.0.3.1xnfqbt++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/lib/QueryCache.js:121:5)
I20151103-19:57:55.561(5.5)?     at new LiveMysqlSelect (/Users/RCMehrotra/.meteor/packages/numtel_mysql/.1.0.3.1xnfqbt++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/lib/LiveMysqlSelect.js:46:16)
I20151103-19:57:55.561(5.5)?     at LiveMysql.select (/Users/RCMehrotra/.meteor/packages/numtel_mysql/.1.0.3.1xnfqbt++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/lib/LiveMysql.js:100:19)
I20151103-19:57:55.561(5.5)?     at [object Object]._handler (server/cumulus-question/question.startup.js:15:18)
I20151103-19:57:55.562(5.5)?     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
I20151103-19:57:55.562(5.5)?     at [object Object]._.extend._runHandler (livedata_server.js:1023:17)
I20151103-19:57:55.562(5.5)? Exception from sub milestones id pD53b9Qic8sBm68gE Error: Cannot enqueue Query after fatal error.
I20151103-19:57:55.562(5.5)?     at Object.Future.wait (/Users/RCMehrotra/.meteor/packages/meteor-tool/.1.1.10.4oz6g6++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
I20151103-19:57:55.562(5.5)?     at LiveMysqlSelect.LiveMysql.LiveMysqlSelect._publishCursor (packages/numtel_mysql/packages/numtel_mysql.js:55:1)
I20151103-19:57:55.563(5.5)?     at [object Object]._.extend._publishHandlerResult (livedata_server.js:1065:13)
I20151103-19:57:55.563(5.5)?     at [object Object]._.extend._runHandler (livedata_server.js:1038:10)
I20151103-19:57:55.563(5.5)?     at [object Object]._.extend._startSubscription (livedata_server.js:842:9)
I20151103-19:57:55.563(5.5)?     at [object Object]._.extend.protocol_handlers.sub (livedata_server.js:614:12)
I20151103-19:57:55.563(5.5)?     at livedata_server.js:548:43
I20151103-19:57:55.563(5.5)?     - - - - -
I20151103-19:57:55.564(5.5)?     at Protocol._validateEnqueue (/Users/RCMehrotra/.meteor/packages/numtel_mysql/.1.0.3.1xnfqbt++os+web.browser+web.cordova/npm/node_modules/mysql/lib/protocol/Protocol.js:193:16)
I20151103-19:57:55.564(5.5)?     at Protocol._enqueue (/Users/RCMehrotra/.meteor/packages/numtel_mysql/.1.0.3.1xnfqbt++os+web.browser+web.cordova/npm/node_modules/mysql/lib/protocol/Protocol.js:129:13)
I20151103-19:57:55.564(5.5)?     at Connection.query (/Users/RCMehrotra/.meteor/packages/numtel_mysql/.1.0.3.1xnfqbt++os+web.browser+web.cordova/npm/node_modules/mysql/lib/Connection.js:201:25)
I20151103-19:57:55.564(5.5)?     at update (/Users/RCMehrotra/.meteor/packages/numtel_mysql/.1.0.3.1xnfqbt++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/lib/QueryCache.js:72:18)
I20151103-19:57:55.564(5.5)?     at QueryCache.invalidate (/Users/RCMehrotra/.meteor/packages/numtel_mysql/.1.0.3.1xnfqbt++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/lib/QueryCache.js:121:5)
I20151103-19:57:55.565(5.5)?     at new LiveMysqlSelect (/Users/RCMehrotra/.meteor/packages/numtel_mysql/.1.0.3.1xnfqbt++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/lib/LiveMysqlSelect.js:46:16)
I20151103-19:57:55.565(5.5)?     at LiveMysql.select (/Users/RCMehrotra/.meteor/packages/numtel_mysql/.1.0.3.1xnfqbt++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/lib/LiveMysql.js:100:19)
I20151103-19:57:55.565(5.5)?     at [object Object]._handler (server/cumulus-question/question.startup.js:22:18)
I20151103-19:57:55.565(5.5)?     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
I20151103-19:57:55.565(5.5)?     at [object Object]._.extend._runHandler (livedata_server.js:1023:17)
I20151103-19:57:55.565(5.5)? Exception from sub question_status id cdADy2iucLqqBBfoq Error: Cannot enqueue Query after fatal error.
I20151103-19:57:55.566(5.5)?     at Object.Future.wait (/Users/RCMehrotra/.meteor/packages/meteor-tool/.1.1.10.4oz6g6++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
I20151103-19:57:55.566(5.5)?     at LiveMysqlSelect.LiveMysql.LiveMysqlSelect._publishCursor (packages/numtel_mysql/packages/numtel_mysql.js:55:1)
I20151103-19:57:55.566(5.5)?     at [object Object]._.extend._publishHandlerResult (livedata_server.js:1065:13)
I20151103-19:57:55.566(5.5)?     at [object Object]._.extend._runHandler (livedata_server.js:1038:10)
I20151103-19:57:55.566(5.5)?     at [object Object]._.extend._startSubscription (livedata_server.js:842:9)
I20151103-19:57:55.567(5.5)?     at [object Object]._.extend.protocol_handlers.sub (livedata_server.js:614:12)
I20151103-19:57:55.567(5.5)?     at livedata_server.js:548:43
I20151103-19:57:55.567(5.5)?     - - - - -
I20151103-19:57:55.567(5.5)?     at Protocol._validateEnqueue (/Users/RCMehrotra/.meteor/packages/numtel_mysql/.1.0.3.1xnfqbt++os+web.browser+web.cordova/npm/node_modules/mysql/lib/protocol/Protocol.js:193:16)
I20151103-19:57:55.567(5.5)?     at Protocol._enqueue (/Users/RCMehrotra/.meteor/packages/numtel_mysql/.1.0.3.1xnfqbt++os+web.browser+web.cordova/npm/node_modules/mysql/lib/protocol/Protocol.js:129:13)
I20151103-19:57:55.567(5.5)?     at Connection.query (/Users/RCMehrotra/.meteor/packages/numtel_mysql/.1.0.3.1xnfqbt++os+web.browser+web.cordova/npm/node_modules/mysql/lib/Connection.js:201:25)
I20151103-19:57:55.568(5.5)?     at update (/Users/RCMehrotra/.meteor/packages/numtel_mysql/.1.0.3.1xnfqbt++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/lib/QueryCache.js:72:18)
I20151103-19:57:55.568(5.5)?     at QueryCache.invalidate (/Users/RCMehrotra/.meteor/packages/numtel_mysql/.1.0.3.1xnfqbt++os+web.browser+web.cordova/npm/node_m

**Comment by khichar-anil** [comment]
@rohitmehrotramedia :
Issue seems with your mysql version 5.0.11. Your way of queries seems according to latest branch.
* For MySQL < 5.1.15, follow the [old branch](https://github.com/numtel/meteor-mysql/tree/old) 
* or upgrade your mysql to >= 5.1.15 to follow [latest branch](https://github.com/numtel/meteor-mysql).

**Comment by numtel** [comment]
Thanks @khichar-anil, that is correct. MySQL 5.1.15 is required for the latest version. The old branch is no longer supported, use at your own discretion.
