### ISSUE TITLE
How to use reactive() in case of terminal conditions

### ISSUE THREAD

**Issue by KrishnaPG** [numtel/meteor-mysql#5]
Thank you for this package - the reactivity is working great with sql backend + binlog combination.

I have a question regarding the terminal conditions though. Consider the below code.
````
// server side
Meteor.publish('queryResults', function () {
    DB.select(this, {
        query: "select * from users where id=\'" + this.userId + "\'",
        triggers: [{
            table: "users",
            condition: function (row, newRow) { return row.id === this.userId; }
        }]
    });
});
````
````
// client js
Template['tmplApi'].created = function() {
    this.resultsColl = new MysqlSubscription("queryResults");
};

Template['tmplApi'].helpers({
    queryResults: function () {
        return Template.instance().resultsColl[0].reactive();
    }
});
````
````
<!-- client HTML !-->
	<hr />
	<label>{{queryResults.name}}</label>
	<label>{{queryResults.id}}</label>
````
A simple records query that works fine for when query results published by server is not empty.

But, when the query results are empty (say the table is empty), then on the clientside, `queryResults[0].reactive()` leads to exception because queryResults[0] is "undefined" and so calling "reactive" on that object is invalid.

In that case, how to handle the situation so that if at all when the table gets updated with proper values, the client can be known. Because this below would solve the undefined problem but would loose the reactivity.
````
Template['tmplApi'].helpers({
    queryResults: function () {
        if (Template.instance().resultsColl.length <= 0) return null;
        return Template.instance().resultsColl[0].reactive();
    }
});
````
Because we are no more returning a reactive object, but returning null and hence client html looses reactivity. What is the work around?

**Comment by numtel** [comment]
The `reactive` method call should come before you access the data by its row index.

e.g. Instead of `resultsColl[0].reactive()`, use `resultsColl.reactive()[0]`.

Try using something like this:

```javascript
Template['tmplApi'].helpers({
    queryResults: function () {
        var subscription = Template.instance().resultsColl.reactive();
        // Return first row, if available
        return subscription.length > 0 ? subscription[0] : null;
    }
})
```

**Comment by KrishnaPG** [comment]
Thank you  - will use this info once I got the re-activity working.
