### ISSUE TITLE
Initial subscription is never ready() after change() and does not return any data

### ISSUE THREAD

**Issue by Twisterking** [numtel/meteor-mysql#52]
Following situation:
On initial load in my router I use
```
allItems = new MysqlSubscription('allItems', null);
```
to subscribe to my publish function which looks like this:
```
Meteor.publish('allItems', function(supplierid){
	if(!empty(supplierid)) {
		var sqlquery = "SELECT * FROM items WHERE supplier_id = " + liveDb.db.escape(supplierid) + " LIMIT 3000";
		return liveDb.select(
			sqlquery,
			[ { table: 'items' } ]
			);
	} else
		return;
});
```

I also have a dropdown select in my template:
```
'change #suppliers': function(event, template) {
	var val = $(event.currentTarget).val();
	if(!empty(val)) {
		Session.set('supplierid', val);
		allItems.change(val);
	}
}
```

So if I understand your docs correctly calling `allItems.change(val);` should change the "supplierid" argument in the publish function and thus update my subscription to get the items of a certain supplierid.
Unfortunately this does **not work**. `allItems.ready()` stays `false` and no data is returned.
What am I doing wrong? :-)

The following **does work** (workaround):
completely deleting the `allItems.change(val);` line and building the subscription in the router like so:
```
allItems = new MysqlSubscription('allItems', Session.get('supplierid'));
```
This does work but this does always create a **new sub** everytime the supplierid Session changes which is not how I should be I think?!

**Comment by hectoroso** [comment]
I'm interested in the answer to this question as well.

**Comment by kiyasov** [comment]
PLS HELP

**Comment by Twisterking** [comment]
In your (iron-)router in the controller for the route do the following:

```
onBeforeAction: function () {
    try {
        allItems.change(this.params._id);
    } catch(err) {
        allItems = new MysqlSubscription('allItems', this.params._id);
    }
    this.next();
}
```

I think this did the trick for me! Was a long time ago so cant give you any more input sorry!
