### ISSUE TITLE
Error: Received packet in the wrong sequence (Two concurrent meteor clients requesting from same SQL DB)

### ISSUE THREAD

**Issue by K808** [numtel/meteor-mysql#56]
Whenever I have two meteor instances (one on a server, one on my machine), both with different SQL users (this doesn't change it), running at the same time/code, the localhost (because it's cycling rebuild) will give the following error while the server meteor is (already) running.  The error goes away if I stop the server meteor instance.  

Even when the local meteor crashes in a loop, both local and server copies display the same data from live sql, as it updates the local copy right before the crash (so two graphs would display the same data).

EDIT: Because of the crash loop, it does miss some data on local.
EDIT2: Not sure what happened, now the error is (Error: Connection lost: The server closed the connection.) on repeat, still fixed on local by stopping server meteor.  

I will have to stop using meteor-mysql because this would not allow multiple servers running the same meteor code to access one database.

Any help would be appreciated! Thanks!

(I saw this issue posted before, but not for two meteors connected to one database)

W20151215-16:47:05.211(-10)? (STDERR) Error: Received packet in the wrong sequence.
W20151215-16:47:05.211(-10)? (STDERR)     at Protocol._parsePacket (/Users//.meteor/packages/numtel_mysql/.1.0.3.1g9ej1j++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/Protocol.js:263:17)
W20151215-16:47:05.211(-10)? (STDERR)     at Parser.write (/Users//.meteor/packages/numtel_mysql/.1.0.3.1g9ej1j++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/Parser.js:77:12)
W20151215-16:47:05.211(-10)? (STDERR)     at Protocol.write (/Users//.meteor/packages/numtel_mysql/.1.0.3.1g9ej1j++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/Protocol.js:39:16)
W20151215-16:47:05.212(-10)? (STDERR)     at Socket.<anonymous> (/Users//.meteor/packages/numtel_mysql/.1.0.3.1g9ej1j++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/Connection.js:82:28)
W20151215-16:47:05.212(-10)? (STDERR)     at Socket.emit (events.js:95:17)
W20151215-16:47:05.212(-10)? (STDERR)     at Socket.<anonymous> (_stream_readable.js:765:14)
W20151215-16:47:05.212(-10)? (STDERR)     at Socket.emit (events.js:92:17)
W20151215-16:47:05.212(-10)? (STDERR)     at emitReadable_ (_stream_readable.js:427:10)
W20151215-16:47:05.212(-10)? (STDERR)     at emitReadable (_stream_readable.js:423:5)
W20151215-16:47:05.212(-10)? (STDERR)     at readableAddChunk (_stream_readable.js:166:9)
W20151215-16:47:05.212(-10)? (STDERR)     --------------------
W20151215-16:47:05.212(-10)? (STDERR)     at Protocol._enqueue (/Users//.meteor/packages/numtel_mysql/.1.0.3.1g9ej1j++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/Protocol.js:135:48)
W20151215-16:47:05.213(-10)? (STDERR)     at Object._start [as _onImmediate] (/Users//.meteor/packages/numtel_mysql/.1.0.3.1g9ej1j++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/index.js:173:31)
W20151215-16:47:05.213(-10)? (STDERR)     at processImmediate [as _immediateCallback] (timers.js:363:15)

W20151215-17:37:14.397(-10)? (STDERR) Error: Connection lost: The server closed the connection.
W20151215-17:37:14.397(-10)? (STDERR)     at Protocol.end (/Users//.meteor/packages/numtel_mysql/.1.0.3.1g9ej1j++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/Protocol.js:103:13)
W20151215-17:37:14.398(-10)? (STDERR)     at Socket.<anonymous> (/Users//.meteor/packages/numtel_mysql/.1.0.3.1g9ej1j++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/Connection.js:88:28)
W20151215-17:37:14.398(-10)? (STDERR)     at Socket.emit (events.js:117:20)
W20151215-17:37:14.398(-10)? (STDERR)     at _stream_readable.js:944:16
W20151215-17:37:14.398(-10)? (STDERR)     at process._tickCallback (node.js:448:13)
W20151215-17:37:14.398(-10)? (STDERR)     --------------------
W20151215-17:37:14.398(-10)? (STDERR)     at Protocol._enqueue (/Users//.meteor/packages/numtel_mysql/.1.0.3.1g9ej1j++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/Protocol.js:135:48)
W20151215-17:37:14.398(-10)? (STDERR)     at Object._start [as _onImmediate] (/Users//.meteor/packages/numtel_mysql/.1.0.3.1g9ej1j++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/index.js:173:31)
W20151215-17:37:14.398(-10)? (STDERR)     at processImmediate [as _immediateCallback] (timers.js:363:15)

**Comment by khichar-anil** [comment]
You must be using same **server-id** in your meteor settings.json file. Make them unique as:
**Server:** server-id = 100
**localhost:** server-id = 101

Please let me know it solves the problem.

**Comment by K808** [comment]
Perfect, that fixed it.  Can't believe I didn't (in brute force effort) try that!  I was thinking the server-id in meteor had to match the ID in my.cnf!
