### ISSUE TITLE
Meteor 1.3 and NPM support: Is this package dead?

### ISSUE THREAD

**Issue by hectoroso** [numtel/meteor-mysql#65]
Now that Meteor 1.3 has direct npm support, and this package is based on the mysql-live-select npm module, will this package continue to be maintained?  I'm assuming it would still be needed for meteor-specific reactive handling, but will it become 1.3 specific?

I ask because we have a site using Meteor 1.2 that is going production soon. It stores mostly in mongo, but uses some data from a mysql db, which is why I'm using this. So it would be great to know the future of this package.

**Comment by numtel** [comment]
This package contains a way to get the query results published to clients. The Node package performs the queries and calculates the differences. If you want to use a different method of getting the data to the client then you may as well use just the Node package. I haven't used Meteor 1.3 yet but if anything breaks, I'll take a look if issues are made.
