### ISSUE TITLE
[Question] where is the _publishCursor called?

### ISSUE THREAD

**Issue by wuxianliang** [numtel/meteor-mysql#8]
Dear @numtel 
I am still debugging my meteor-orientdb project which insert console.logs everywhere to see which part is working. I have seen the _setRows works and data in LiveMysqlSelect is fullfiled, but I did not find who called _publishCursor method. There is data in select instance. But I can not see them at client side. So I am working on publishing and subscription further.

Thank you very much.

**Comment by numtel** [comment]
It's called when you publish an object

https://github.com/meteor/meteor/blob/59ac39ce81cac85cd733ec91f2be74b4d8251e59/packages/ddp/livedata_server.js#L933

**Comment by wuxianliang** [comment]
Thank you. I have seen data on the screen. Now it is time to working on reactivity when data is changed.
