### ISSUE TITLE
How to show Busy UI while subscriptions are being waited for updates?

### ISSUE THREAD

**Issue by KrishnaPG** [numtel/meteor-mysql#9]
Hoping you could throw some light on something I have been trying to figure out, but couldn't.

The situation is like this:

I am using MysqlSubscription on Meteor server.

    1. On the client side HTML I have a button that when clicked makes a meteor server call
    2. Meteor server creates new values and pushes into SQL DB
    3. Meteor server's subscriptions get updated through SQL DB's binop log updates
    4. And through your magic package client receives the updates.

The question, while all this is happening "from button click on html" to "results coming back through subscriptions", there is slight time gap, and I would like to show a "busy" spinner on HTML UI on client side.

I can start the spinner in the button click handler. But how to know when to stop it.

That is: after button is clicked on the client side, how to know when the client's subscriptions have been updated successfully?

If there is some kind of callback to let the client know whenever the subscriptions have been updated, then the spinner can be stopped inside the callback.

Any pointers?

**Comment by numtel** [comment]
Check out the [leaderboard example's usage of method stubs](https://github.com/numtel/meteor-mysql-leaderboard/blob/master/leaderboard.js#L11-31). It simulates the updated values but you could just as well use a spinner.
